### ISSUE TITLE
需求0.0

### ISSUE THREAD

**Issue by lscLucienLee** [lscLucienLee/Parallel-corpus-management-system#1]
响应时间：
1.	创建语料库：在提交请求后，系统应立即创建一个新的语料库，并返回创建成功的信息。
2.	更新语料库：在提交新语料后，系统应立即更新语料库，并返回更新成功的信息。
3.	合并语料库：在提交请求后，系统应立即合并两个指定的语料库，并返回合并成功的信息。
4.	拆分语料库：在提交请求后，系统应立即拆分指定语料库，并返回拆分成功的信息。
5.	过滤语料库：在执行过滤操作后，系统应立即返回符合条件的语料，响应时间不应超过5秒。
6.	去重语料库：在执行去重操作后，系统应立即返回删除的重复语料数量，并更新语料库。
7.	规范化语料库：在执行规范化操作后，系统应立即返回规范化成功的语料数量，并更新语料库。
8.	浏览/查询：在执行浏览/查询功能时，系统应立即返回符合条件的语料列表，响应时间不应超过5秒。
9.	分析统计：在执行分析统计操作后，系统应立即返回统计结果，响应时间不应超过10秒。
10.	翻译结果自动评价：在执行翻译结果自动评价操作后，系统应立即返回评价结果，响应时间不应超过10秒。
11.	翻译结果人工评价：在执行翻译结果人工评价操作后，系统应立即返回评价结果，响应时间不应超过10秒。
12.	对齐：在执行对齐操作后，系统应立即返回对齐成功的语料数量，并更新语料库。

安全性：
1.	只有经过授权的用户才能访问平行语料管理系统。
2.	不同用户之间的数据应该互相隔离。
3.	未授权的用户不应能够重置密码或者修改帐户信息。
4.	用户数据应该进行加密存储。
5.	用户应能够设置密码策略，强制其员工使用强密码。
6.	系统应对非法登录尝试进行监控或者报警。
7.	对敏感操作如删除、合并语料库，应设置二次确认的安全选项。 

可扩展性：
1.	系统应支持不同类型的平行语料，如文本、音频、视频。
2.	系统应支持多种语言间的平行语料。
3.	系统应支持多种数据存储方式，并支持多种关系型和非关系型数据库。
4.	平行语料管理系统应该可以与其他机器翻译系统进行接口对接和数据交换。
5.	系统应支持虚拟化技术和容器技术，以便部署在不同的环境下。 

易用性：
1.	系统应该有易于使用的图形用户界面，使得用户可以直观地操作。
2.	系统应支持批量操作，例如批量上传、删除、导出等操作。
3.	系统应支持多语言界面，以方便不同地区的用户使用。
4.	系统应支持可配置的通知和提醒功能，例如任务完成、用户登录等事件。
5.	系统应提供完善的文档和培训资料，使得用户可以快速上手和使用系统。

**Comment by VielotYZH** [comment]
第一个标题，“响应时间”应该改为“初步需求”。
